#ifndef __DRIVER_MOTORSEVERBASE_H
#define __DRIVER_MOTORSEVERBASE_H
#include "Driver_MotorSever.h"
#include "Driver_MotorSeverInit.h"
#include "Driver_MotorSeverList.h"
//???????
motorConfigStruct_t commandoMotorConfig[USE_LIST];
//??????
uint8_t	histSend_mark[CAN_NET_LIST];
//???????
motorConfigStruct_t infantryMotorConfig[USE_LIST] = {
	//Yaw?????0
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,INFANTRY_YAW,{CAN1_0X2FF_NET,CONTROL_NET},&RevYaw,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//Pitch?????1
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,INFANTRY_PITCH,{CAN1_0X2FF_NET,CONTROL_NET},&RevPitch,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????2
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???????3
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,INFANTRY_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????4
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,INFANTRY_SUPPLY,{CAN1_0X1FF_NET,CONTROL_NET},&RevSupply,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????5
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,INFANTRY_FRIC_L,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????6
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,INFANTRY_FRIC_R,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????7
	{{M1502A_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,CHASSIS_RF,{CAN2_0X1FF_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],M1502A_MotorUpdata,M1502A_MotorReviece,NULL,STANDBY},
	//????????8
	{{M1502A_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,CHASSIS_LF,{CAN2_0X1FF_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],M1502A_MotorUpdata,M1502A_MotorReviece,NULL,STANDBY},
	//ÂÖì±3508??9
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,0x203,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//??3508??10
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,0x204,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//11»¬¿é1 6020 ID1
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,0x205,{CAN1_0X1FF_NET,CHASSIS_NET},&RevArm,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//12»¬¿é2 6020 ID2
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,0x206,{CAN1_0X1FF_NET,CHASSIS_NET},&RevSynchronous,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};
//????????
motorConfigStruct_t p_tankMotorConfig[USE_LIST] = {
	//Yaw????? 0
	{{RMD_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x141,P_TANK_YAW,{CAN2_0X142_NET,CONTROL_NET},&RevYaw,RMD_MotorUpdata,RMD_MotorReviece,NULL,STANDBY},
	//Pitch????? 1
    {{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN2,0x2FF,INFANTRY_PITCH,{CAN2_0X2FF_NET,CONTROL_NET},&RevPitch,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????	//????? 2
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???(???)???? 3
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???(???)???? 4
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????? 5
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????? 6
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????????? 7
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????? 8
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????? 9 
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????? 10
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????(slave)???? 11 
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????(slave)???? 12
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???(???)???? 13
	{{RM_MOTOR,INCREASING_250HZ_B,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,P_TANK_BIG_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???(???)???? 14
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};
//????????
motorConfigStruct_t f_tankMotorConfig[USE_LIST] = {
	//Yaw?????
	{{RMD_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x141,F_TANK_YAW,{CAN1_0X141_NET,CONTROL_NET},&RevYaw,RMD_MotorUpdata,RMD_MotorReviece,NULL,STANDBY},
	//Pitch?????
	{{RMD_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN2,0x142,F_TANK_PITCH,{CAN2_0X142_NET,CONTROL_NET},&RevPitch,RMD_MotorUpdata,RMD_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,F_TANK_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,F_TANK_SUPPLY,{CAN1_0X1FF_NET,CONTROL_NET},&RevSupply,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,F_TANK_FRIC_L,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,F_TANK_FRIC_R,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????(???)????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,F_TANK_ARM,{CAN2_0X1FF_NET,CHASSIS_NET},&RevArm,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????(???)????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,F_TANK_SYNCHRONOUS,{CAN2_0X1FF_NET,CHASSIS_NET},&RevSynchronous,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};
//???????
motorConfigStruct_t auxiliayMotorConfig[USE_LIST] = {
	//RMD_MotorUpdata
	{{RMD_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x141,AUXILIARY_YAW,{CAN1_0X141_NET,CONTROL_NET},&RevYaw,RMD_MotorUpdata,RMD_MotorReviece,NULL,STANDBY},
	//Pitch?????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,AUXILIARY_PITCH,{CAN1_0X200_NET,CONTROL_NET},&RevPitch,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x200,AUXILIARY_FRONT_CLAW,{CAN2_0X200_NET,CONTROL_NET},&RevClaw,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//??????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x200,AUXILIARY_LIFT_ELEVATOR,{CAN2_0X200_NET,CONTROL_NET},&RevEle[ELE_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//??????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x200,AUXILIARY_RIGHT_ELEVATOR,{CAN2_0X200_NET,CONTROL_NET},&RevEle[ELE_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,AUXILIARY_LIFT_REVERSING,{CAN2_0X1FF_NET,CONTROL_NET},&RevRev[REV_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,AUXILIARY_RIGHT_REVERSING,{CAN2_0X1FF_NET,CONTROL_NET},&RevRev[REV_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
//	//X?????	
//	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x200,AUXILIARY_X_SLIDEWAY,{CAN2_0X200_NET,CONTROL_NET},&RevSwy[SWY_X],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
//	//Y?????
//	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN2,0x1FF,AUXILIARY_Y_SLIDEWAY,{CAN2_0X1FF_NET,CONTROL_NET},&RevSwy[SWY_Y],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},

};
//???????
motorConfigStruct_t sentryMotorConfig[USE_LIST] = {
	//Yaw?????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,SENTRY_YAW,{CAN1_0X2FF_NET,CONTROL_NET},&RevYaw,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//Pitch?????
	{{RMD_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x142,SENTRY_PITCH,{CAN1_0X142_NET,CONTROL_NET},&RevPitch,RMD_MotorUpdata,RMD_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SENTRY_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SENTRY_FRIC_L,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SENTRY_FRIC_R,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//??????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LF,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LF_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_LB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[LB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//??????????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x200,CHASSIS_RB,{CAN1_0X200_NET,CHASSIS_NET},&RevChassis[RB_WHEEL],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_B,STANDBY},{STANDBY,STANDBY},CAN1,0x200,SENTRY_DIRECT,{CAN1_0X200_NET,CONTROL_NET},&RevDirect,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};
//??????????
motorConfigStruct_t smgMotorConfig[USE_LIST] = {
	//Yaw?????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,SMALLGIMBAL_YAW,{CAN1_0X2FF_NET,CONTROL_NET},&RevYaw,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//Pitch?????
	{{RM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,SMALLGIMBAL_PITCH,{CAN1_0X2FF_NET,CONTROL_NET},&RevPitch,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SMALLGIMBAL_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SMALLGIMBAL_FRIC_L,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,SMALLGIMBAL_FRIC_R,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};

//LCM: ??UAV?????
//UAV
motorConfigStruct_t uavMotorConfig[USE_LIST] = {
	//Yaw?????
	{{GM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,UAV_YAW,{CAN1_0X2FF_NET,CONTROL_NET},&RevYaw,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//Pitch?????
	{{GM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,UAV_PITCH,{CAN1_0X2FF_NET,CONTROL_NET},&RevPitch,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//Roll?????
	{{GM_MOTOR,INCREASING_500HZ,STANDBY},{STANDBY,STANDBY},CAN1,0x2FF,UAV_ROLL,{CAN1_0X2FF_NET,CONTROL_NET},&RevRoll,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//???????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,UAV_POKE,{CAN1_0X1FF_NET,CONTROL_NET},&RevPoke,RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,UAV_FRIC_L,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_L],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//????????
	{{RM_MOTOR,INCREASING_250HZ_F,STANDBY},{STANDBY,STANDBY},CAN1,0x1FF,UAV_FRIC_R,{CAN1_0X1FF_NET,CONTROL_NET},&RevFric[FRIC_R],RM_MotorUpdata,RM_MotorReviece,NULL,STANDBY},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
	//?????
	{{NO_MOTOR,DEAFULT_FREQ,NO_PARAMETER},{NO_PARAMETER,NO_PARAMETER},NO_TYPE,NO_IDENTIFIER,NO_IDENTIFIER,{DEAFULT_CAN_NET,DEAFULT_NET},NULL,NULL,NULL,NULL,NO_PARAMETER},
};

#endif

